In [1]:
import torch

In [2]:
a = torch.randn(2,3)

In [3]:
a

tensor([[ 1.0628, -0.4108,  0.7000],
        [-1.2468, -1.6652,  0.1126]])

In [4]:
a.type()

'torch.FloatTensor'

In [5]:
torch.Tensor

torch.Tensor

In [6]:
isinstance(a,torch.FloatTensor)

True

In [7]:
isinstance(a,torch.cuda.FloatTensor)

False

In [8]:
a = a.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [9]:
isinstance(a,torch.cuda.FloatTensor)

False

In [16]:
a = torch.Tensor(0)

In [17]:
a.shape

torch.Size([0])

In [18]:
len(a.shape)

1

In [19]:
a.size()

torch.Size([0])

In [20]:
torch.Tensor([1.1])

tensor([1.1000])

In [21]:
torch.Tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [22]:
torch.Tensor(1)

tensor([0.])

In [23]:
a = torch.ones(2)

In [24]:
a.shape

torch.Size([2])

In [25]:
a = torch.randn(2,3)

In [26]:
a

tensor([[ 1.4277,  0.9194,  1.7564],
        [ 1.4344, -0.1898,  0.4087]])

In [27]:
a.shape

torch.Size([2, 3])

In [28]:
a.size(0)

2

In [29]:
a.size(1)

3

In [31]:
a.shape[0]
a.shape[1]

3

In [32]:
a = torch.rand(1,2,3)
a

tensor([[[0.4336, 0.1537, 0.5737],
         [0.6614, 0.1803, 0.2257]]])

In [33]:
list(a.shape)

[1, 2, 3]

In [34]:
a = torch.rand(2,3,28,28)
a

tensor([[[[0.0920, 0.1888, 0.8892,  ..., 0.5509, 0.6408, 0.6020],
          [0.0799, 0.8631, 0.1112,  ..., 0.5993, 0.5437, 0.2340],
          [0.0330, 0.9817, 0.4983,  ..., 0.7006, 0.8949, 0.4064],
          ...,
          [0.7343, 0.8552, 0.4253,  ..., 0.6390, 0.1767, 0.3035],
          [0.6860, 0.4564, 0.7817,  ..., 0.7040, 0.6537, 0.6920],
          [0.3168, 0.7932, 0.5249,  ..., 0.1626, 0.1453, 0.4444]],

         [[0.4154, 0.6167, 0.8677,  ..., 0.0776, 0.5989, 0.0053],
          [0.6465, 0.5018, 0.3266,  ..., 0.5617, 0.5693, 0.2505],
          [0.9153, 0.9276, 0.4650,  ..., 0.1799, 0.6647, 0.0518],
          ...,
          [0.9314, 0.8905, 0.4438,  ..., 0.4336, 0.8196, 0.2123],
          [0.0351, 0.3184, 0.0958,  ..., 0.5043, 0.6400, 0.2230],
          [0.4383, 0.0403, 0.2429,  ..., 0.8286, 0.4362, 0.9468]],

         [[0.8203, 0.9083, 0.0758,  ..., 0.7260, 0.0808, 0.2262],
          [0.3380, 0.5989, 0.3612,  ..., 0.6593, 0.5478, 0.4329],
          [0.8181, 0.7021, 0.9676,  ..., 0

In [36]:
a.numel()

4704

In [38]:
a.dim()

4

In [40]:
a = torch.Tensor(1)
a.dim()

1